name = "noflare-demo"
main = "src/examples/index.ts"
compatibility_date = "2024-12-05"

[[workflows]]
name = "calculate-cube"
binding = "CALCULATE_CUBE_WORKFLOW"
class_name = "CalculateCubeWorkflow"

[[kv_namespaces]]
binding = "NUMBER_STORE"
id = "01928374650987654321"